# Generated by Django 4.2.2 on 2023-11-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Titulo')),
                ('codigo_video', models.TextField(blank=True, null=True, verbose_name='Código de incorporação')),
                ('texto', models.TextField(verbose_name='Texto Principal')),
                ('categoria', models.CharField(choices=[('papelao', 'Papelão'), ('vidro', 'Vidro'), ('plastico', 'Plástico')], max_length=15, verbose_name='Categoria')),
            ],
        ),
    ]
